#!/usr/bin/env ruby

$LOAD_PATH << "lib"
$LOAD_PATH << "models"

require 'trail'
require 'environment'

Environment.environment = 'test'

def menu
  puts <<-EOS
_-_ Welcome to Blaze-cli! _-_

Please choose a number:
  1. Log a trail
  2. View log
  3. Search log
EOS
end

def get_menu_selection
  puts menu
  input = gets
  return unless input
  input.chomp!
  if input == "1"
    add_trail
  elsif input == "2"
    puts "Your Blaze-cli trail log:"
  elsif input == "3"
    puts "Select what you'd like to search:"
  else
    puts "'#{input}' is not valid. Please try again."
    get_menu_selection
  end
end

def add_trail
  puts "What is the trail name?"
  trail_name = gets.chomp
  trail = Trail.new(trail_name)
  if trail.save
    puts "#{trail_name} has been added."
  else
    puts injury.errors
    add_trail
  end
end

get_menu_selection
